<div class="panel panel-default">
    <div class="panel-heading">
        Produto
    </div>
 <?php echo $this->form()->openTag($form)?>
    <div class="panel-body">
 
        <div class="form-group">
            <label for="categoria"><?php echo $this->formLabel($form->get('categoria'))?></label>
            <?php echo $this->formElement($form->get('categoria'))?>
            <?php echo $this->formElementErrors($form->get('categoria'))?>            
        </div> 
     
        <div class="form-group">
            <label for="nome"><?php echo $this->formLabel($form->get('nome'))?></label>
            <?php echo $this->formElement($form->get('nome'))?>
            <?php echo $this->formElementErrors($form->get('nome'))?>            
        </div> 
        
        <div class="form-group">
            <label for="slug"><?php echo $this->formLabel($form->get('slug'))?></label>
            <?php echo $this->formElement($form->get('slug'))?>
            <?php echo $this->formElementErrors($form->get('slug'))?>            
        </div> 
        
        <div class="form-group">
            <label for="descricao"><?php echo $this->formLabel($form->get('descricao'))?></label>
            <?php echo $this->formElement($form->get('descricao'))?>
            <?php echo $this->formElementErrors($form->get('descricao'))?>            
        </div> 
        
        
        <div class="form-group">
            <label for="preco"><?php echo $this->formLabel($form->get('preco'))?></label>
            <?php echo $this->formElement($form->get('preco'))?>
            <?php echo $this->formElementErrors($form->get('preco'))?>            
        </div> 
        
        
        <div class="form-group">
            <label for="peso"><?php echo $this->formLabel($form->get('peso'))?></label>
            <?php echo $this->formElement($form->get('peso'))?>
            <?php echo $this->formElementErrors($form->get('peso'))?>            
        </div> 
        
        <div class="form-group">
            <label for="ativo"><?php echo $this->formLabel($form->get('ativo'))?></label>
            <?php echo $this->formElement($form->get('ativo'))?>
            <?php echo $this->formElementErrors($form->get('ativo'))?>            
        </div> 
     

    </div>
     <div class="panel-footer">
         <input type="button" onclick="document.location.href='/admin/<?php echo $controller?>'" class="btn btn-primary" value="Voltar">
         <input type="submit" value="Salvar" class="btn btn-primary">

             
     </div>
 <?php echo $this->form()->closeTag($form)?>
</div>