<div class="panel panel-default">
    <div class="panel-heading">
        Usuário
    </div>
 <?php echo $this->form()->openTag($form)?>
    <div class="panel-body">
 
        <div class="form-group">
            <label for="perfil"><?php echo $this->formLabel($form->get('perfil'))?></label>
            <?php echo $this->formElement($form->get('perfil'))?>
            <?php echo $this->formElementErrors($form->get('perfil'))?>            
        </div> 
     
        <div class="form-group">
            <label for="nome"><?php echo $this->formLabel($form->get('nome'))?></label>
            <?php echo $this->formElement($form->get('nome'))?>
            <?php echo $this->formElementErrors($form->get('nome'))?>            
        </div> 
        
        <div class="form-group">
            <label for="email"><?php echo $this->formLabel($form->get('email'))?></label>
            <?php echo $this->formElement($form->get('email'))?>
            <?php echo $this->formElementErrors($form->get('email'))?>            
        </div> 
        
        <div class="form-group">
            <label for="senha"><?php echo $this->formLabel($form->get('senha'))?></label>
            <?php echo $this->formElement($form->get('senha'))?>
            <?php echo $this->formElementErrors($form->get('senha'))?>            
        </div> 
        
        <div class="form-group">
            <label for="status"><?php echo $this->formLabel($form->get('status'))?></label>
            <?php echo $this->formElement($form->get('status'))?>
            <?php echo $this->formElementErrors($form->get('status'))?>            
        </div> 
     

    </div>
     <div class="panel-footer">
         <input type="button" onclick="document.location.href='/admin/<?php echo $controller?>'" class="btn btn-primary" value="Voltar">
         <input type="submit" value="Salvar" class="btn btn-primary">

             
     </div>
 <?php echo $this->form()->closeTag($form)?>
</div>