<div class="panel panel-default">
    <div class="panel-heading">
        Resource
    </div>
 <?php echo $this->form()->openTag($form)?>
    <div class="panel-body">
   
        <div class="form-group">
            <label for="nome"><?php echo $this->formLabel($form->get('nome'))?></label>
            <?php echo $this->formElement($form->get('nome'))?>
            <?php echo $this->formElementErrors($form->get('nome'))?>            
        </div> 

    </div>
     <div class="panel-footer">
         <input type="button" onclick="document.location.href='/admin/<?php echo $controller?>'" class="btn btn-primary" value="Voltar">
         <input type="submit" value="Salvar" class="btn btn-primary">

             
     </div>
 <?php echo $this->form()->closeTag($form)?>
</div>