<div class="panel panel-default">
    <div class="panel-heading">
        <a href="<?php echo $this->url('admin/default', array('controller' => $controller, 'action' => 'cadastrar')); ?>" class="btn btn-primary">Novo Atributo</a>
    </div>

    <div class="panel-body">
        <form name="form" action="" method="get">
            <table class="table">
                <thead>
                    <tr>
                        <td>ID</td>
                        <td>Nome</td>
                        <td>Tipo Seleção</td>
                        <td>Opções</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><input type="text" name="id" value="<?php echo isset($filtro['id']) ? $filtro['id'] : "" ?>"></td>
                        <td><input type="text" name="nome" value="<?php echo isset($filtro['id']) ? $filtro['nome'] : "" ?>"></td>
                        <td><input type="text" name="nome" value="<?php echo isset($filtro['id']) ? $filtro['tipo_selecao'] : "" ?>"></td>
                        <td>
                            <input class="btn" type="submit" value="filtrar">
                        </td>
                    </tr>
                    <?php
                    if (count($data)):
                        foreach ($data as $item):
                            ?>
                            <tr>
                                <td><?php echo $item->getId() ?></td>
                                <td><?php echo $item->getNome() ?></td>
                                <td><?php
                                    switch ($item->getTipoSelecao()):
                                        case 1:
                                            echo 'Radio';
                                            break;
                                        case 2:
                                            echo 'Checkbox';
                                            break;
                                        case 3:
                                            echo 'Select';
                                            break;
                                        default :
                                            echo '---';
                                     endswitch;
                                  
                                        
                                     ?></td>
                                <td>
                                    <a href="<?php echo $this->url('admin/default', array('controller' => $controller, 'action' => 'editar', 'id' => $item->getId())) ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                                    <a href="<?php echo $this->url('admin/default', array('controller' => $controller, 'action' => 'delete', 'id' => $item->getId())) ?>" onClick="return confirm('Deseja Excluir ?')"><i class="glyphicon glyphicon-remove"></i></a>



                                </td>
                            </tr>
                            <?php
                        endforeach;
                    endif;
                    ?>
                </tbody>           
            </table>
        </form>
    </div>
    <div class="panel-footer" style="text-align: center;">

<?php echo $this->paginationControl($data, 'sliding', 'partials/paginator.phtml') ?>

    </div>
</div>